version: '3.8'

services:
  # Init container to register runner 1
  gitlab-runner-1-init:
    image: alpine:latest
    container_name: gitlab-runner-1-init
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - RUNNER_TAG_LIST=${RUNNER_1_TAGS:-runner-1,docker}
      - RUNNER_NAME=${RUNNER_1_NAME:-GitLab Runner 1}
      - RUNNER_LIMIT=${RUNNER_1_LIMIT:-10}
    volumes:
      - ./register-runner.sh:/register.sh:ro
      - runner-1-config:/etc/gitlab-runner
    command: ["/bin/sh", "/register.sh"]
    networks:
      - gitlab-runner-network

  gitlab-runner-1:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner-1
    depends_on:
      gitlab-runner-1-init:
        condition: service_completed_successfully
    environment:
      - FF_USE_ADAPTIVE_REQUEST_CONCURRENCY=true
      - FF_NETWORK_PER_BUILD=true
      - DOCKER_DRIVER=overlay2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-1-config:/etc/gitlab-runner
      - runner-1-cache:/cache
    restart: unless-stopped
    networks:
      - gitlab-runner-network

  # Init container to register runner 2
  gitlab-runner-2-init:
    image: alpine:latest
    container_name: gitlab-runner-2-init
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - RUNNER_TAG_LIST=${RUNNER_2_TAGS:-runner-2,docker}
      - RUNNER_NAME=${RUNNER_2_NAME:-GitLab Runner 2}
      - RUNNER_LIMIT=${RUNNER_2_LIMIT:-10}
    volumes:
      - ./register-runner.sh:/register.sh:ro
      - runner-2-config:/etc/gitlab-runner
    command: ["/bin/sh", "/register.sh"]
    networks:
      - gitlab-runner-network

  gitlab-runner-2:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner-2
    depends_on:
      gitlab-runner-2-init:
        condition: service_completed_successfully
    environment:
      - FF_USE_ADAPTIVE_REQUEST_CONCURRENCY=true
      - FF_NETWORK_PER_BUILD=true
      - DOCKER_DRIVER=overlay2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-2-config:/etc/gitlab-runner
      - runner-2-cache:/cache
    restart: unless-stopped
    networks:
      - gitlab-runner-network

  # Init container to register runner 3
  gitlab-runner-3-init:
    image: alpine:latest
    container_name: gitlab-runner-3-init
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - RUNNER_TAG_LIST=${RUNNER_3_TAGS:-runner-3,docker}
      - RUNNER_NAME=${RUNNER_3_NAME:-GitLab Runner 3}
      - RUNNER_LIMIT=${RUNNER_3_LIMIT:-10}
    volumes:
      - ./register-runner.sh:/register.sh:ro
      - runner-3-config:/etc/gitlab-runner
    command: ["/bin/sh", "/register.sh"]
    networks:
      - gitlab-runner-network

  gitlab-runner-3:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner-3
    depends_on:
      gitlab-runner-3-init:
        condition: service_completed_successfully
    environment:
      - FF_USE_ADAPTIVE_REQUEST_CONCURRENCY=true
      - FF_NETWORK_PER_BUILD=true
      - DOCKER_DRIVER=overlay2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-3-config:/etc/gitlab-runner
      - runner-3-cache:/cache
    restart: unless-stopped
    networks:
      - gitlab-runner-network

volumes:
  runner-1-config:
  runner-2-config:
  runner-3-config:
  runner-1-cache:
  runner-2-cache:
  runner-3-cache:

networks:
  gitlab-runner-network:
    driver: bridge
